CREATE TABLE ciudades (
 idCiudad  INT NOT NULL PRIMARY KEY,
 nomCiudad  VARCHAR(15), 
 nomProvincia      VARCHAR(15)
);

INSERT INTO ciudades VALUES (10,'ARANJUEZ','MADRID');
INSERT INTO ciudades VALUES (20,'CHINCHON','MADRID');
INSERT INTO ciudades VALUES (30,'SEGOVIA','SEGOVIA');
INSERT INTO ciudades VALUES (40,'MERIDA','BADAJOZ');

CREATE TABLE monumentos (
 idMonumento    INT  NOT NULL PRIMARY KEY,
 nomMonumento  VARCHAR(25), 
 idCiudad   INT NOT NULL REFERENCES ciudades(idCiudad)
);
INSERT INTO monumentos VALUES (7010,'PALACIO REAL',10);
INSERT INTO monumentos VALUES (7020,'PLAZA MAYOR',20);
INSERT INTO monumentos VALUES (7030,'ACUEDUCTO ROMANO',30);
INSERT INTO monumentos VALUES (7040,'TEATRO ROMANO',40);

COMMIT;